//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProxyService.WCFPerfSample {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFPerfSample.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        Contracts.LogInfo GetData(Contracts.LogInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<Contracts.LogInfo> GetDataAsync(Contracts.LogInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AsyncGetData", ReplyAction="http://tempuri.org/IService1/AsyncGetDataResponse")]
        Contracts.LogInfo AsyncGetData(Contracts.LogInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AsyncGetData", ReplyAction="http://tempuri.org/IService1/AsyncGetDataResponse")]
        System.Threading.Tasks.Task<Contracts.LogInfo> AsyncGetDataAsync(Contracts.LogInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuperAsyncGetData", ReplyAction="http://tempuri.org/IService1/SuperAsyncGetDataResponse")]
        Contracts.LogInfo SuperAsyncGetData(Contracts.LogInfo value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuperAsyncGetData", ReplyAction="http://tempuri.org/IService1/SuperAsyncGetDataResponse")]
        System.Threading.Tasks.Task<Contracts.LogInfo> SuperAsyncGetDataAsync(Contracts.LogInfo value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfProxyService.WCFPerfSample.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfProxyService.WCFPerfSample.IService1>, WcfProxyService.WCFPerfSample.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Contracts.LogInfo GetData(Contracts.LogInfo value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<Contracts.LogInfo> GetDataAsync(Contracts.LogInfo value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Contracts.LogInfo AsyncGetData(Contracts.LogInfo value) {
            return base.Channel.AsyncGetData(value);
        }
        
        public System.Threading.Tasks.Task<Contracts.LogInfo> AsyncGetDataAsync(Contracts.LogInfo value) {
            return base.Channel.AsyncGetDataAsync(value);
        }
        
        public Contracts.LogInfo SuperAsyncGetData(Contracts.LogInfo value) {
            return base.Channel.SuperAsyncGetData(value);
        }
        
        public System.Threading.Tasks.Task<Contracts.LogInfo> SuperAsyncGetDataAsync(Contracts.LogInfo value) {
            return base.Channel.SuperAsyncGetDataAsync(value);
        }
    }
}
